### ISSUE TITLE
Deploying multiplue instances of the same problem will sometimes result in a xinetd crash

### ISSUE THREAD

**Issue by sdlinn** [picoCTF/picoCTF#103]
`(picoCTF-env) root@pico-local-dev-shell:/etc/xinetd.d# shell_manager deploy -r -n 5 "ECB 1"
Traceback (most recent call last):
  File "/picoCTF-env/bin/shell_manager", line 11, in <module>
    load_entry_point('ctf-shell-manager==1.2.1', 'console_scripts', 'shell_manager')()
  File "/picoCTF-env/lib/python3.6/site-packages/shell_manager/run.py", line 281, in main
    args.func(args, config)
  File "/picoCTF-env/lib/python3.6/site-packages/hacksport/deploy.py", line 878, in deploy_problems
    debug=args.debug)
  File "/picoCTF-env/lib/python3.6/site-packages/hacksport/deploy.py", line 728, in deploy_problem
    instance["socket_file"])
  File "/picoCTF-env/lib/python3.6/site-packages/hacksport/deploy.py", line 473, in install_user_service
    execute(["service", "xinetd", "start"], timeout=60)
  File "/picoCTF-env/lib/python3.6/site-packages/hacksport/operations.py", line 50, in execute
    return process.wait_for_result()
  File "/picoCTF-env/lib/python3.6/site-packages/spur/local.py", line 182, in wait_for_result
    self._result = self._generate_result()
  File "/picoCTF-env/lib/python3.6/site-packages/spur/local.py", line 194, in _generate_result
    stderr_output
  File "/picoCTF-env/lib/python3.6/site-packages/spur/results.py", line 11, in result
    raise result.to_error()
spur.results.RunProcessError: return code: 1
output: b''
stderr output: b'Job for xinetd.service failed. See "systemctl status xinetd.service" and "journalctl -xe" for details.\n'`

Every time a new instance is created, 
`execute(["service", "xinetd", "restart"], timeout=60)'
is called from install_user_service. 

This needs to be changed to only restart once, after all of the instances have been created.

**Comment by sdlinn** [comment]
This has been fixed in Mutli instance fix #104
