### ISSUE TITLE
Mass deployment xinetd errors

### ISSUE THREAD

**Issue by al3xfulton** [picoCTF/picoCTF#117]
While the errors that have appeared in mass deployment are generally revolving around xinetd deployment I hoped would be fixed with port deconfliction however they continue to occur at seemingly random intervals. After a couple of runs of the mass script (in the problems directory for reference) it is an inconsistent set of problems which will fail initially on deployement, manually deploying using ```sudo shell manager deploy package-name``` acts as anticipated with no errors after the fact. Not sure where this problem stems from, but it appears to only occur when running many deploy commands in rapid succession. A sample error message is below for reference:

```Deploying Problem: netcat/problem.json
Traceback (most recent call last):
  File "/usr/local/bin/shell_manager", line 11, in <module>
    load_entry_point('ctf-shell-manager==1.2.1', 'console_scripts', 'shell_manager')()
  File "/picoCTF-env/lib/python3.6/site-packages/shell_manager/run.py", line 281, in main
    args.func(args, config)
  File "/picoCTF-env/lib/python3.6/site-packages/hacksport/deploy.py", line 901, in deploy_problems
    debug=args.debug)
  File "/picoCTF-env/lib/python3.6/site-packages/hacksport/deploy.py", line 799, in deploy_problem
    execute(["service", "xinetd", "restart"], timeout=60)
  File "/picoCTF-env/lib/python3.6/site-packages/hacksport/operations.py", line 50, in execute
    return process.wait_for_result()
  File "/picoCTF-env/lib/python3.6/site-packages/spur/local.py", line 182, in wait_for_result
    self._result = self._generate_result()
  File "/picoCTF-env/lib/python3.6/site-packages/spur/local.py", line 194, in _generate_result
    stderr_output
  File "/picoCTF-env/lib/python3.6/site-packages/spur/results.py", line 11, in result
    raise result.to_error()
spur.results.RunProcessError: return code: 1
output: b''
stderr output: b'Job for xinetd.service failed. See "systemctl status xinetd.service" and "journalctl -xe" for details.\n'```

**Comment by carlislemc** [comment]
This sounds like a timing issue. How many problems were you deploying? Perhaps you could try changing restart in deploy.py to stop followed by start (and put a delay in if needed)

**Comment by carlislemc** [comment]
Good news is this only runs 1x per problem, not per instance as previous

**Comment by hiliang-cmu** [comment]
> Job for xinetd.service failed. See "systemctl status xinetd.service" and "journalctl -xe" for details.

What do those say?

**Comment by al3xfulton** [comment]
This includes a good chunk of those outputs - including a full deployment (or more accurately redeployment) cycle in there.

[journalctl.txt](https://github.com/picoCTF/picoCTF/files/2217380/journalctl.txt)
[status.txt](https://github.com/picoCTF/picoCTF/files/2217381/status.txt)
